async (page) => {
  const base = new URL(page.url()).origin;
  const checks = [], errors = [];
  const assert = (condition, message) => { if (!condition) throw new Error(message); checks.push(message); };
  const state = () => page.evaluate(() => ({ ...takeoff.getState(), audio: takeoff.getAudioState() }));
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/');
  assert((await state()).audio.context === 'uninitialized', 'No audio context or playback before user interaction');
  await page.getByRole('button', { name: '开启环境音', exact: true }).click();
  await page.waitForTimeout(600);
  const audible = await state();
  assert(audible.playing && audible.sound && audible.audio.active && audible.audio.level > 0.005, 'Enabling sound starts the tour and produces measurable audio');
  await page.getByRole('button', { name: '关闭环境音', exact: true }).click();
  await page.waitForTimeout(450);
  assert((await state()).playing && !(await state()).sound && (await state()).audio.context === 'suspended', 'Muting suspends the audio context while the tour continues');
  await page.getByRole('button', { name: '开启环境音', exact: true }).click();
  await page.waitForTimeout(300);
  await page.getByRole('button', { name: '暂停漫游' }).click();
  await page.waitForTimeout(450);
  assert(!(await state()).playing && (await state()).sound && (await state()).audio.context === 'suspended', 'Pausing silences audio and preserves the sound preference');
  await page.getByRole('button', { name: '自动漫游' }).click();
  await page.waitForTimeout(400);
  assert((await state()).audio.active && (await state()).audio.level > 0.005, 'Resuming restores audible ambient sound');
  await page.getByRole('button', { name: '关闭环境音', exact: true }).click();
  await page.getByRole('button', { name: '开启环境音', exact: true }).click();
  await page.getByRole('button', { name: '关闭环境音', exact: true }).click();
  await page.waitForTimeout(450);
  assert(!(await state()).sound && (await state()).audio.context === 'suspended', 'Rapid sound toggles settle in the last requested muted state');
  await page.getByRole('button', { name: '开启环境音', exact: true }).click();
  await page.getByRole('button', { name: '暂停漫游' }).click();
  await page.getByRole('button', { name: '自动漫游' }).click();
  await page.waitForTimeout(450);
  assert((await state()).playing && (await state()).audio.active && (await state()).audio.level > 0.005, 'Rapid pause and resume preserve the newest audio request');
  await page.getByRole('button', { name: '探索世界' }).click();
  await page.waitForTimeout(450);
  assert(!(await state()).playing && (await state()).audio.context === 'suspended', 'Opening the destination atlas stops ambient playback');
  await page.getByRole('button', { name: '关闭目的地目录' }).click();
  assert(errors.length === 0, 'No runtime errors during audio acceptance');
  return { checks, errors, audibleLevel: audible.audio.level };
}
